scala_library(name='scala',
  provides = scala_artifact(
    org = 'com.twitter',
    name = 'scrooge-core',
    repo = artifactory,
  ),
  dependencies=[
    '3rdparty:libthrift-0.9.1'
  ],
  sources=rglobs('*.scala'),
)
