/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package thrift;

import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.apache.thrift.*;
import org.apache.thrift.async.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.transport.*;
import org.apache.thrift.protocol.*;

// No additional import required for struct/union.

public class HomeTakedown implements TBase<HomeTakedown, HomeTakedown._Fields>, java.io.Serializable, Cloneable {
  private static final TStruct STRUCT_DESC = new TStruct("HomeTakedown");

  private static final TField UNUSED_FIELD_DESC = new TField("unused", TType.STRING, (short)1);


  public String unused;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements TFieldIdEnum {
    UNUSED((short)1, "unused");
  
    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();
  
    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }
  
    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // UNUSED
  	return UNUSED;
        default:
  	return null;
      }
    }
  
    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }
  
    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }
  
    private final short _thriftId;
    private final String _fieldName;
  
    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }
  
    public short getThriftFieldId() {
      return _thriftId;
    }
  
    public String getFieldName() {
      return _fieldName;
    }
  }


  // isset id assignments

  public static final Map<_Fields, FieldMetaData> metaDataMap;
  static {
    Map<_Fields, FieldMetaData> tmpMap = new EnumMap<_Fields, FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.UNUSED, new FieldMetaData("unused", TFieldRequirementType.OPTIONAL,
      new FieldValueMetaData(TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    FieldMetaData.addStructMetaDataMap(HomeTakedown.class, metaDataMap);
  }


  public HomeTakedown() {
  }


  /**
   * Performs a deep copy on <i>other</i>.
   */
  public HomeTakedown(HomeTakedown other) {
    if (other.isSetUnused()) {
      this.unused = other.unused;
    }
  }

  public HomeTakedown deepCopy() {
    return new HomeTakedown(this);
  }

  @Override
  public void clear() {
    this.unused = null;
  }

  public String getUnused() {
    return this.unused;
  }

  public HomeTakedown setUnused(String unused) {
    this.unused = unused;
    
    return this;
  }

  public void unsetUnused() {
    this.unused = null;
  }

  /** Returns true if field unused is set (has been asigned a value) and false otherwise */
  public boolean isSetUnused() {
    return this.unused != null;
  }

  public void setUnusedIsSet(boolean value) {
    if (!value) {
      this.unused = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case UNUSED:
      if (value == null) {
        unsetUnused();
      } else {
        setUnused((String)value);
      }
      break;
    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case UNUSED:
      return getUnused();
    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case UNUSED:
      return isSetUnused();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof HomeTakedown)
      return this.equals((HomeTakedown)that);
    return false;
  }

  public boolean equals(HomeTakedown that) {
    if (that == null)
      return false;
    boolean this_present_unused = true && this.isSetUnused();
    boolean that_present_unused = true && that.isSetUnused();
    if (this_present_unused || that_present_unused) {
      if (!(this_present_unused && that_present_unused))
        return false;
      if (!this.unused.equals(that.unused))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();
    boolean present_unused = true && (isSetUnused());
    builder.append(present_unused);
    if (present_unused)
      builder.append(unused);
    return builder.toHashCode();
  }

  public int compareTo(HomeTakedown other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    HomeTakedown typedOther = (HomeTakedown)other;

    lastComparison = Boolean.valueOf(isSetUnused()).compareTo(typedOther.isSetUnused());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUnused()) {
      lastComparison = TBaseHelper.compareTo(this.unused, typedOther.unused);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) {
        break;
      }
      switch (field.id) {
        case 1: // UNUSED
          if (field.type == TType.STRING) {
            this.unused = iprot.readString();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();
    
    oprot.writeStructBegin(STRUCT_DESC);
    if (this.unused != null) {
      if (isSetUnused()) {
        oprot.writeFieldBegin(UNUSED_FIELD_DESC);
        oprot.writeString(this.unused);
        oprot.writeFieldEnd();
      }
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("HomeTakedown(");
    boolean first = true;
    if (isSetUnused()) {
      sb.append("unused:");
      if (this.unused == null) {
        sb.append("null");
      } else {
        sb.append(this.unused);
      }
      first = false;
      }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
  }
}
